### ISSUE TITLE
Módulo escolas - GET - Obter dados de uma escola específica

### ISSUE THREAD

**Issue by nataliasou** [umarley/seteAPI#101]
![image](https://user-images.githubusercontent.com/45390353/187096497-2224bcca-519d-4457-b7b6-6a513ecf10a2.png)
Exemplo de requisição:
GET https://sete.transportesufg.eng.br/escolas/5201405/85
Resultado:
•	Retorno do HTTP está 200 (OK)
•	O resultado está diferente do esperado na API
•	Está usando o seguinte formato 
{ ..., result: "true" }
•	Os últimos quatro campos de cada usuário estão como NULL e possui link, verificar se é o correto com o Prof.  Marcos e o Umarley
![image](https://user-images.githubusercontent.com/45390353/187096538-3c58900c-d0c6-429a-9170-928d876c9eb8.png)

Exemplo de requisição:
GET https://sete.transportesufg.eng.br/escolas/5201405/0
Resultado:
•	Retorno do HTTP é 404 – Not Found
•	O resultado não está documentado na API
•	Está usando o seguinte formato 
{ “links”: ..., result: "false" }
•	Não possui mensagem de erro e possui links, verificar com o professor se isso está certo
![image](https://user-images.githubusercontent.com/45390353/187096554-8d27c0ae-c579-48bc-8b6f-d8ff40fd7b31.png)

Exemplo de requisição:
GET https://sete.transportesufg.eng.br/escolas/0/85
Resultado:
•	Retorno do HTTP é 400 – Bad request
•	O resultado não está documentado na API
•	Está usando o seguinte formato 
{ result: "false", “messages”: “string” }
![image](https://user-images.githubusercontent.com/45390353/187096584-d85e8c42-fe55-4cc9-8249-776ac5373c54.png)

Exemplo de requisição:
GET https://sete.transportesufg.eng.br/escolas/111111111111/85
Resultado:
•	Retorno do HTTP é 404 – Not found
•	O resultado não está documentado na API
•	Está usando o seguinte formato 
{ result: "false", “messages”: “string” }
![image](https://user-images.githubusercontent.com/45390353/187096597-61739e39-2b36-4909-bcd4-8f6ef09f5c03.png)

**Comment by nataliasou** [comment]
@umarley 
Obs. Não coloquei o "_links"

```
get:
      tags:
      - escolas
      summary: Obter os dados de uma escola especifica
      produces:
      - application/json
      parameters:
      - name: codigo_cidade
        in: path
        description: Código do municipio
        required: true
        type: integer
        format: int64
      - name: id_escola
        in: path
        description: ID da Escola que se deseja obter
        required: true
        type: integer
        format: int64
      responses:
        200:
          description:  Operação realizada com sucesso.
          schema:
            $ref: '#/definitions/EscolaEspecifica'
        400:
          description: Parâmetros incorretos
        404:
          description: Recurso não encontrado.
      security:
      - api_key: []
  ```

Models:
```
EscolaEspecifica:
    type: object
    properties:
      codigo_cidade:
        type: integer
      id_escola:
        type: integer
      nome:
        type: string
      mec_co_entidade:
        type: integer
      mec_co_uf:
        type: integer  
      mec_co_municipio:
        type: integer
      mec_no_entidade:
        type: string
      mec_tp_dependencia:
        type: integer
        description: Tipo de dependência da escola 1. Federal 2. Estadual 3. Municipal 4. Privada
        enum:
        - 1
        - 2
        - 4
      mec_tp_localizacao:
        type: integer
        description: Localização da escola 1. Urbana 2. Rural
        enum:
        - 1
        - 2
        - 4
      mec_in_regular:
        type: string
        description: Escola oferta ensino regular? S = Sim N = Não
        enum:
        - S
        - N  
      mec_in_eja:
        type: string
        description: Escola oferta ensino para jovens e adultos? S = Sim N = Não
        enum:
        - S
        - N
      mec_in_profissionalizante:
        type: string
        description: Escola oferta ensino profissionalizante? S = Sim N = Não
        enum:
        - S
        - N
      mec_in_especial_exclusiva:
        type: string
        description: Escola oferta ensino especial? S = Sim N = Não
        enum:
        - S
        - N
      loc_latitude:
        type: string
      loc_longitude:
        type: string
      loc_cep:
        type: string  
      loc_endereco:
        type: string  
      contato_responsavel:
        type: string
      contato_telefone:
        type: string
      contato_email:
        type: string
      horario_matutino:
        type: string
        description: Escola funciona no horário matutino? S = Sim N = Não
        enum:
        - S
        - N
      horario_vespertino:
        type: string
        description: Escola funciona no horário vespertino? S = Sim N = Não
        enum:
        - S
        - N
      horario_noturno:
        type: string
        description: Escola funciona no horário noturno? S = Sim N = Não
        enum:
        - S
        - N
      ensino_superior:
        type: string
        description: Escola oferece ensino superior? S = Sim N = Não
        enum:
        - S
        - N
      ensino_medio:
        type: string
        description: Escola oferece ensino médio? S = Sim N = Não
        enum:
        - S
        - N
      ensino_fundamental:
        type: string
        description: Escola oferece ensino fundamental? S = Sim N = Não
        enum:
        - S
        - N
      ensino_pre_escola:
        type: string
        description: Escola oferece ensino pré-escola? S = Sim N = Não
        enum:
        - S
        - N  
      mec_tp_localizacao_diferenciada:
        type: integer
        description: Localização da escola 1. Área de Assentamento 2. Terra Indígena 3. Área remanescente de Quilombo 7. Não se aplica
        enum:
        - 1
        - 2
        - 3
        - 7
      codigo_escola_firebase:
        type: string
      alterado_por:
        type: string
      dt_criacao:
        type: string
      criado_por:
        type: string
      dt_alteracao:
        type: string
      result:
        type: boolean
```
