### ISSUE TITLE
Módulo monitores - GET - Obter dados de um monitor específico

### ISSUE THREAD

**Issue by nataliasou** [umarley/seteAPI#105]
![image](https://user-images.githubusercontent.com/45390353/187096994-05fbe3c1-678c-475a-aff0-6965c2382b90.png)
Exemplo de requisição:
GET https://sete.transportesufg.eng.br/monitores/5201405/74966706009
Resultado:
•	Retorno do HTTP é 200 - Ok
•	A documentação não possui resultado esperado
•	Está usando o seguinte formato 
{ ..., result: true }
•	Está com alguns campos nulos como latitude e longitude, verificar se isso está correto.
![image](https://user-images.githubusercontent.com/45390353/187097007-78441bb3-3a6e-4ce0-a4d2-e451a5dd9ab3.png)

Exemplo de requisição:
GET https://sete.transportesufg.eng.br/monitores/5201405/0
Resultado:
•	Retorno do HTTP é 404 – Not found
•	A documentação não possui resultado esperado
•	Está usando o seguinte formato 
{ result: "false"}
•	Retornou alguns resultados estranhos e não retornou mensagem de erro, verificar se isso está correto.
![image](https://user-images.githubusercontent.com/45390353/187097018-21b0c410-a697-4244-8549-1d8fa3ee9045.png)

Exemplo de requisição:
GET https://sete.transportesufg.eng.br/monitores/5201405/0
Resultado:
•	Retorno do HTTP é 404 – Not found
•	A documentação não possui resultado esperado
•	Está usando o seguinte formato 
{ result: "false"}
•	Retornou alguns resultados estranhos e não retornou mensagem de erro, verificar se isso está correto.
![image](https://user-images.githubusercontent.com/45390353/187097026-83412ab5-7776-4ef7-8392-d6d9c0c67115.png)

Exemplo de requisição:
GET https://sete.transportesufg.eng.br/monitores/0/0
Resultado:
•	Retorno do HTTP é 400 – Bad request
•	A documentação não possui resultado esperado
•	Está usando o seguinte formato 
{ result: "false", messages: “string”}
![image](https://user-images.githubusercontent.com/45390353/187097039-462bfbe9-487e-4a14-ab35-a0e3cc62da09.png)

**Comment by nataliasou** [comment]
@umarley 
```
get:
      tags:
      - monitores
      summary: Obter dados de um monitor específico
      operationId: getMonitorId
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: codigo_cidade
        description: Código do municipio que a rota pertence
        required: true
        type: integer
      - in: path
        name: cpf_monitor
        description: CPF do monitor que se deseja consultar 
        required: true
        type: integer
      responses:
        200:
          description: Operação realizada com sucesso
          schema:
              $ref: '#/definitions/MonitorEspecifico'
        400:
          description: Parâmetros incorretos
        404:
          description: Recurso não encontrado.
      security:
      - api_key: []
```

Models:

```
MonitorEspecifico:
    ListaUsuario:
    properties:
      codigo_cidade:
        type: integer
      nome:
        type: string
      cpf:
        type: string
      data_nascimento:
        description: Data de nascimento no formato dd/mm/yyyy
        type: string
      sexo:
        type: integer
        description: Sexo do Motorista 1. Masculino 2. Feminino 3. Não Informado
        enum:
        - 1
        - 2
        - 3
      telefone:
        type: string
      vinculo:
        type: integer
        description: Vínculo do motorista com a administração pública 1. Servidor efetivo 2. Servidor comissionado 3. Servidor terceirizado 4. Outro
        enum:
        - 1
        - 2
        - 3
        - 4
      salario:
        type: number
        description: Salário pago ao monitor
      turno_manha:
        type: string
        description: Trabalha no turno da manhã? S = Sim N = Não
        enum:
        - S
        - N
      turno_tarde:
        type: string
        description: Trabalha no turno da tarde? S = Sim N = Não
        enum:
        - S
        - N
      turno_noite:
        type: string
        description: Trabalha no turno da noite? S = Sim N = Não
        enum:
        - S
        - N
      loc_latitude:
        type: string
      loc_longitude:
        type: string
      dt_criacao:
        description: Data de criação no formato dd/mm/yyyy
        type: string
      criado_por:
        type: string
      dt_alteracao:
        description: Data de alteração no formato dd/mm/yyyy
        type: string
      alterado_por:
        type: string
      result:
        type: boolean
```
