### ISSUE TITLE
Módulo ordemServico - GET - Obter a lista de ordens de serviços de um município

### ISSUE THREAD

**Issue by nataliasou** [umarley/seteAPI#109]
![image](https://user-images.githubusercontent.com/45390353/187098128-ea1c2bca-9be1-401d-877d-48783e73858c.png)

Exemplo de requisição:
GET https://sete.transportesufg.eng.br/ordens-servicos/5201405
Resultado:
•	Retorno do HTTP é 200 - OK
•	O resultado não está documentado na API
•	Está usando o seguinte formato 
{ ..., “total”: 0, result: "true" }
•	Alguns cometarios estão como string e outros como null e possui links no resultado, verificar se é o correto com o Prof.  Marcos e o Umarley

![image](https://user-images.githubusercontent.com/45390353/187098121-10a97594-f448-4ebb-ae67-8cd6edac3fbe.png)

Exemplo de requisição:
GET https://sete.transportesufg.eng.br/ordens-servicos/0
Resultado:
•	Retorno do HTTP é 400 – Bad request
•	O resultado não está documentado na API
•	Está usando o seguinte formato 
{ result: "false", “messages”: “string” }

![image](https://user-images.githubusercontent.com/45390353/187098160-46e1de26-47a6-4b57-b064-e462bf10e3dc.png)

**Comment by nataliasou** [comment]
@umarley 
Obs. não coloquei "_links"

```
get:
      tags:
      - ordemServico
      summary: Obter a lista de ordens de serviços de um município
      operationId: getOrdemServico
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: codigo_cidade
        description: Código do municipio que a ordem de serviço pertence
        required: true
        type: integer
      responses:
        200:
          description: Operação realizada com sucesso
          schema:
              $ref: '#/definitions/allOrdemServico'
        400:
          description: Parâmetros incorretos
      security:
      - api_key: []
 ```

Model:

```
allOrdemServico:
    type: object
    properties:
      data:
        type: array
        items:
          type: object
          properties:
            id_ordem:
              type: integer
            id_veiculo:
              type: integer
            id_fornecedor:
              type: integer
            data:
              type: string
              description: Data da Ordem de serviço no formato dd/mm/yyyy
            tipo_servico:
              type: integer
              description: Tipo do serviço 1. Combustível 2. Lubrificante 3. Pag. Seguro 4. Man. Preventiva 5. Manutenção 
              enum:
              - 1
              - 2
              - 3
              - 4
              - 5
            comentario:
              type: string
            termino:
              type: string
      total:
        type: integer
      result:
        type: boolean
```
