### ISSUE TITLE
Módulo normas - GET - Obter a lista de normas cadastradas de um município

### ISSUE THREAD

**Issue by nataliasou** [umarley/seteAPI#112]
![image](https://user-images.githubusercontent.com/45390353/187098578-eaecd6da-50be-4c28-8b19-37766cad3201.png)
Exemplo de requisição:
GET https://sete.transportesufg.eng.br/normas/5201405
Resultado:
•	Retorno do HTTP é 200 - Ok
•	O resultado não está documentado na API.
•	Está usando o seguinte formato 
{ ..., “total”: 0, result: "true" }
•	“outro_tipo” e “assuntos” estão nulos, verificar se é o correto com o Prof.  Marcos e o Umarley
![image](https://user-images.githubusercontent.com/45390353/187098637-6d08e07e-94b2-4fe9-8e6e-7cedf40765de.png)

Exemplo de requisição:
GET https://sete.transportesufg.eng.br/normas/0
Resultado:
•	Retorno do HTTP é 400 – Bad request
•	O resultado não está documentado na API.
•	Está usando o seguinte formato 
{ result: false, “messages”: “string” }

![image](https://user-images.githubusercontent.com/45390353/187098654-936fc6d8-a6ef-4ee2-b1ec-94fae2f74bec.png)

Exemplo de requisição:
GET https://sete.transportesufg.eng.br/normas/1111111
Resultado:
•	Retorno do HTTP é 404 – Not found
•	O resultado não está documentado na API.
•	Está usando o seguinte formato 
{ result: false, “messages”: “string” }

![image](https://user-images.githubusercontent.com/45390353/187098659-7dfea039-a68a-46ea-9a7f-c9ffe547944a.png)

**Comment by nataliasou** [comment]
@umarley 

```
get:
      tags:
      - normas
      summary: Obter a lista de normas cadastradas de um município
      operationId: getNormas
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: codigo_cidade
        description: Código do municipio que a norma pertence.
        required: true
        type: integer
      responses:
        200:
          description: Operação realizada com sucesso
          schema:
              $ref: '#/definitions/allNormas'
        400:
          description: Parâmetros incorretos.
        404:
          description: Recurso não encontrado.
      security:
      - api_key: []
 ```

Model:
```
allNormas:
    type: object
    properties:
      data:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
            titulo:
              type: string
            id_tipo:
              type: integer
            outro_tipo:
              type: integer
            data_norma:
              type: string
              description: Data da norma no formato dd/mm/yyyy
            assuntos:
              type: array
              items:
                type: string
      total:
        type: integer
      result:
        type: boolean
```
