### ISSUE TITLE
Módulo Alunos - GET - Obter os dados de um aluno especifico

### ISSUE THREAD

**Issue by glcalil-ufg** [umarley/seteAPI#117]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-2ce7162b-7fff-3454-afdc-8ccb7c063bb4"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:567px;height:52px;"><img src="https://lh3.googleusercontent.com/JpesnmN08D9mBJn-hYyqqqXsGUnL52JegDs117hhYzuCYs8w49H8Es9Z0YWkX_MxGQ_vQvfoh8x4rA8jNl0i4F_MK0a4ajfs46oVuT-jHVZbQzz5VBeNGRUuvLJ2sRx5wi3a5epMc5FknbmcE1OuMTo" width="567" height="52" style="margin-left:0px;margin-top:0px;" /></span></span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Exemplo de requisição:</span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:9pt;font-family:Consolas,sans-serif;color:#212121;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">GET </span><a href="https://sete.transportesufg.eng.br/alunos/5201405/1" style="text-decoration:none;"><span style="font-size:9pt;font-family:Consolas,sans-serif;color:#0563c1;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">https://sete.transportesufg.eng.br/alunos/5201405/1</span></a></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Resultado do experimento:</span></p><ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Retorno do HTTP está 200 (OK)</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">O resultado está diferente do esperado na API</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Está usando o seguinte formato&nbsp;</span></p></li></ul><p dir="ltr" style="line-height:1.295;margin-left: 36pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Consolas,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">{ ..., result: &quot;true&quot; }</span></p><ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Há vários campos NULL, verificar se é o correto com o Prof.&nbsp; Marcos e o Umarley</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Há campos do tipo _links, deve ser feito assim mesmo?</span></p></li></ul><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:602px;height:499px;"><img src="https://lh3.googleusercontent.com/FMsRkHO20LK5hUyTF3OIwE4Ns822qQTGlMkndl8Z_HzmFHX33WiwmL8jFl5gTtn5YEFvIPdgULpLnqLtsmA155nfQxgioOShtv7wTO05-J8lNAQl4VIGNO_Ajws6nGYID1teEqZELueqOQJOusmgsfjiHR2AuIfpNWnB9qYjLpLm0lzYGX4kO7tm4Q" width="602" height="499" style="margin-left:0px;margin-top:0px;" /></span></span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="width:100px;display:inline-block;position:relative;"></span></span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Exemplo de requisição:</span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:9pt;font-family:Consolas,sans-serif;color:#212121;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">GET </span><a href="https://sete.transportesufg.eng.br/alunos/5201405/999999" style="text-decoration:none;"><span style="font-size:9pt;font-family:Consolas,sans-serif;color:#1155cc;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">https://sete.transportesufg.eng.br/alunos/5201405/999999</span></a></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Resultado do experimento:</span></p><br /><ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Retorno do HTTP está 404 (NOT FOUND)</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">O resultado está diferente do esperado na API</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Está usando o seguinte formato&nbsp;</span></p></li></ul><p dir="ltr" style="line-height:1.295;margin-left: 36pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Consolas,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">{ ..., result: &quot;false&quot; }</span></p><ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Há campos do tipo _links, deve ser feito assim mesmo?</span></p></li></ul><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:582px;height:158px;"><img src="https://lh3.googleusercontent.com/XcNjjvTp-HRjtJAYZNXni1pWGyUBUWNhcElYoom7ju2C10_jZYFuLt0iP2d0xmgiHWGinXnCTR9HH1dGyWPnyqSTazweTMl_1EUYuK9476e58vZRHBqIovi_atacLlEZx_SCBfebG8z1GRX13a5MON21WUqwS1DTnmesdE41CqEig-2AJKyBBc63Fw" width="582" height="158" style="margin-left:0px;margin-top:0px;" /></span></span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Exemplo de requisição:</span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:9pt;font-family:Consolas,sans-serif;color:#212121;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">GET </span><a href="https://sete.transportesufg.eng.br/alunos/5201405999/1" style="text-decoration:none;"><span style="font-size:9pt;font-family:Consolas,sans-serif;color:#1155cc;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">https://sete.transportesufg.eng.br/alunos/5201405999/1</span></a></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Resultado do experimento:</span></p><ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Retorno do HTTP está 404 (NOT FOUND)</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">O resultado está diferente do esperado na API</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Está usando o seguinte formato&nbsp;</span></p></li></ul><p dir="ltr" style="line-height:1.295;margin-left: 36pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Consolas,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">{ result: &quot;false&quot;, messages : &ldquo;...&rdquo; }</span></p><br /><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:Consolas,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:578px;height:112px;"><img src="https://lh3.googleusercontent.com/66qw_FypXPwAJ-QUMmxLZGgdkgCYTpbVHpW4fI13ai14XuINGDyp_Ezz6Vj1CFNi5BVTDnTGRORvYWsR7r-bzf3U5CkSUcfeoAlePqhNr-c0_D38QgTNaI6ra67JAXpAb5LI3a3LplSY44shiL17dZPOVm-NG4hMmsAY_HzMajNAkPhij4en1BLP5g" width="578" height="112" style="margin-left:0px;margin-top:0px;" /></span></span></p><br /><div dir="ltr" style="margin-left:-5.4pt;" align="left">

</div><br /><br /></b>
</body>
</html>

**Comment by glcalil-ufg** [comment]
@umarley 
```yaml
get:
      tags:
      - alunos
      summary: Obter os dados de um aluno especifico
      description: Returns a single pet
      operationId: getPetById
      produces:
      - application/json
      parameters:
      - in: path
        name: codigo_cidade
        type: integer
        description: Código da cidade do aluno a ser atualizado
        required: true
      - name: id_aluno
        in: path
        description: Id do aluno buscado
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: Operação realizada com sucesso
          schema:
            $ref: '#/definitions/AlunoRetorno'
        400:
          description: Parametros incorretos
        404:
          description: Aluno não encontrado
      security:
      - api_key: []
 ```
Modelo
```yaml
AlunoRetorno:
    type: object
    required:
     - mec_tp_localizacao
     - nome
     - data_nascimento
     - sexo
     - cor
     - nivel
     - turno
    properties:
      codigo_cidade:
        type: integer
      id_aluno:
        type: integer
      loc_latitude:
        type: string
      loc_longitude:
        type: string
      loc_endereco:
        type: string
      loc_cep:
        type: string
      da_porteira:
        type: string
        description: Tem porteira? S = Sim N = Não
        enum:
        - S
        - N
      da_mataburro:
        type: string
        description: Tem mata-burro? S = Sim N = Não
        enum:
        - S
        - N
      da_colchete:
        type: string
        description: Tem colchete? S = Sim N = Não
        enum:
        - S
        - N
      da_atoleiro:
        type: string
        description: Tem atoleiro? S = Sim N = Não
        enum:
        - S
        - N
      da_ponterustica:
        type: string
        description: Tem ponte rústica? S = Sim N = Não
        enum:
        - S
        - N
      nome:
        type: string
      data_nascimento:
        description: Data de nascimento no formato dd/mm/yyyy
        type: string
      sexo:
        type: integer
        description: Sexo do Aluno 1. Masculino 2. Feminino 3. Não Informado
        enum:
        - 1
        - 2
        - 3
      cor:
        type: integer
        description: Cor/raça do Aluno 0. Não informada 1. Amarelo 2. Branco 3. Indigena 4. Pardo 5. Preto
        enum:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
      turno:
        type: integer
        description: Turno de estudo do Aluno 1. Matutino 2. Vespertino 3. Integral 4. Noturno
        enum:
        - 1
        - 2
        - 3
        - 4
      nivel:
        type: integer
        description: Nível do Aluno 1. Infantil 2. Fundamental 3. Médio 4. Superior 5. Outro
        enum:
        - 1
        - 2
        - 3
        - 4
        - 5
      nome_responsavel:
        type: string
      grau_responsavel:
        type: integer
        description: Grau de parentesco -1; Não informado 0. Pai, Mãe, Padrasto ou Madrasta 1. Avô ou Avó 2. Irmão ou Irmã 4. Outro Parente
        enum:
        - 0
        - 1
        - 2
        - 4
      mec_tp_localizacao:
        type: integer
        description: Localização do Aluno 1. Urbana 2. Rural
        enum:
        - 1
        - 2
      cpf:
        type: string
      def_caminhar:
        type: string
        description: Tem deficiência fisica? S = Sim N = Não
        enum:
        - S
        - N
      def_ouvir:
        type: string
        description: Tem deficiência auditiva? S = Sim N = Não
        enum:
        - S
        - N
      def_enxergar:
        type: string
        description: Tem deficiência visual? S = Sim N = Não
        enum:
        - S
        - N
      def_mental:
        type: string
        description: Tem deficiência mental? S = Sim N = Não
        enum:
        - S
        - N
    xml:
      name: Aluno
```
