### ISSUE TITLE
Módulo Alunos - GET - Obter dados da rota associada ao aluno

### ISSUE THREAD

**Issue by glcalil-ufg** [umarley/seteAPI#119]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-960463cf-7fff-e1dd-5c74-bd143f71e831"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:567px;height:51px;"><img src="https://lh3.googleusercontent.com/PXUhoeZ80a5ZHQM6uQxUsdYxvU7xaaDHDQtqs3b2JR1VkRYP_W6qXDTFjVZclo-dg2QN0gQ2sBg-VC5aS6htkV8BW9zkfv3frHX3dmt2ZnuNNNL1zaRORh3qOCjVoAz3FCx0IywomooT" width="567" height="51" style="margin-left:0px;margin-top:0px;" /></span></span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Exemplo de requisição:</span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:9pt;font-family:Consolas,sans-serif;color:#212121;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">GET </span><a href="https://sete.transportesufg.eng.br/alunos/5201405/9/rota" style="text-decoration:none;"><span style="font-size:9pt;font-family:Consolas,sans-serif;color:#1155cc;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">https://sete.transportesufg.eng.br/alunos/5201405/9/rota</span></a></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Resultado do experimento:</span></p><ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Retorno do HTTP está 200 (OK)</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">O resultado está diferente do esperado na API</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Está usando o seguinte formato&nbsp;</span></p></li></ul><p dir="ltr" style="line-height:1.295;margin-left: 36pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Consolas,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">{ ..., result: &quot;true&quot; }</span></p><ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Há vários campos NULL, verificar se é o correto com o Prof.&nbsp; Marcos e o Umarley</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Campo shape abreviado neste documento para melhor leitura da response</span></p></li></ul><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:585px;height:345px;"><img src="https://lh4.googleusercontent.com/UrETHNfSKZT9YwwpCd7_Q7WYyDMQQWZLj4TGEbVrAkLNCt5q6_G_Cun5TNPWzosuZjAmYxCyRKuiEOQOIhpWVRgl09F3Z1EuEY7NKqIKKFgJ3cVt60yMbt2upFHSxDOgI7khCXOqx1C1" width="585" height="345" style="margin-left:0px;margin-top:0px;" /></span></span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Exemplo de requisição:</span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:9pt;font-family:Consolas,sans-serif;color:#212121;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">GET </span><a href="https://sete.transportesufg.eng.br/alunos/5201405999/9/rota" style="text-decoration:none;"><span style="font-size:9pt;font-family:Consolas,sans-serif;color:#1155cc;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">https://sete.transportesufg.eng.br/alunos/5201405999/9/rota</span></a></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Resultado do experimento:</span></p><ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Retorno do HTTP está 404 (NOT FOUND)</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">O resultado está diferente do esperado na API</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Está usando o seguinte formato&nbsp;</span></p></li></ul><p dir="ltr" style="line-height:1.295;margin-left: 36pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Consolas,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">{ result: &quot;false&quot;, messages : &ldquo;...&rdquo; }</span></p><br /><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Consolas,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:580px;height:86px;"><img src="https://lh5.googleusercontent.com/rzUMT3uSgBlm5ippVmA4QVHI5XtCgx6ytku1V0l901Nmd24xPRlsjpdFI9TW7t-YZvUdSpibCJHMrPT4nMPv2wVAuTbFIpP6Q5hb_0E1VnXkfq7ULsSgIWtbCI8-SUekW3_fRCej15Qq" width="580" height="86" style="margin-left:0px;margin-top:0px;" /></span></span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Exemplo de requisição:</span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:9pt;font-family:Consolas,sans-serif;color:#212121;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">GET </span><a href="https://sete.transportesufg.eng.br/alunos/5201405/263189/rota" style="text-decoration:none;"><span style="font-size:9pt;font-family:Consolas,sans-serif;color:#1155cc;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">https://sete.transportesufg.eng.br/alunos/5201405/</span><span style="font-size:8pt;font-family:Consolas,sans-serif;color:#1155cc;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">263189</span><span style="font-size:9pt;font-family:Consolas,sans-serif;color:#1155cc;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">/rota</span></a></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Resultado do experimento:</span></p><ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Retorno do HTTP está 404 (NOT FOUND)</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">O resultado está diferente do esperado na API</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Mesma resposta para alunos sem rota cadastrada ou &lt;id_aluno&gt; incorreto</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Está usando o seguinte formato&nbsp;</span></p></li></ul><p dir="ltr" style="line-height:1.295;margin-left: 36pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Consolas,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Erro não capturado, { result: &quot;false&quot; }</span></p><br /><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:Consolas,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:579px;height:159px;"><img src="https://lh6.googleusercontent.com/KRAH51-BYWnPZiAbV5YJGUjAm5jwE9o1VwAKJJImZP-VJG0Ea9R13_c8fXkRfG2FvO50jwV8BbbiLV7SiMKND-g42Rp64U6KsgvXCOk4lo3fM-IzXJJRSimjZsZpWZaHPcJ8Pz9fooTE" width="579" height="159" style="margin-left:0px;margin-top:0px;" /></span></span></p><br /><div dir="ltr" style="margin-left:-5.4pt;" align="left">

</div></b>
</body>
</html>

**Comment by glcalil-ufg** [comment]
@umarley 
```yaml
get:
      tags:
      - alunos
      summary: Obter os dados da rota associada ao aluno
      description: Retornar a rota associada ao cadastro do aluno
      operationId: getRotaAluno
      produces:
      - application/json
      parameters:
      - in: path
        name: codigo_cidade
        type: integer
        description: Código da cidade do aluno a ser atualizado
        required: true
      - name: id_aluno
        in: path
        description: ID do aluno que se deseja consultar a rota vinculada
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: Operação realizada com sucesso
          schema:
            $ref: '#/definitions/RotaAluno'
        400:
          description: Dados inválidos
        404:
          description: Rota não encontrada
```

Modelo 
``` yaml
RotaAluno:
    type: object
    properties:
      id_aluno:
        type: integer
      id_rota:
        type: integer
      codigo_cidade:
        type: integer
      nome:
        type: string
      km:
        description: Tamanho da rota (em km)
        type: number
      hora_ida_inicio:
        description: Horário de inicio da Ida no formato hh:mm
        type: string
      hora_ida_termino:
        description: Horário de inicio da Volta no formato hh:mm
        type: string
      da_porteira:
        type: string
        description: Tem porteira? S = Sim N = Não
        enum:
        - S
        - N
      da_mataburro:
        type: string
        description: Tem mata-burro? S = Sim N = Não
        enum:
        - S
        - N
      da_colchete:
        type: string
        description: Tem colchete? S = Sim N = Não
        enum:
        - S
        - N
      da_atoleiro:
        type: string
        description: Tem atoleiro? S = Sim N = Não
        enum:
        - S
        - N
      da_ponterustica:
        type: string
        description: Tem ponte rústica? S = Sim N = Não
        enum:
        - S
        - N
      turno_matutino:
        type: string
        description: Funciona no turno da manhã? S = Sim N = Não
        enum:
        - S
        - N
      turno_vespertino:
        type: string
        description: Funciona no turno da tarde? S = Sim N = Não
        enum:
        - S
        - N
      turno_noturno:
        type: string
        description: Funciona no turno da noite? S = Sim N = Não
        enum:
        - S
        - N
      shape:
        description: JSON do traçado da rota de forma vetorial
        type: string
      hora_volta_inicio:
        description: Horário de inicio da Volta no formato hh:mm
        type: string
      hora_volta_termino:
        description:  Horário de término da Volta no formato hh:mm
        type: string
      tempo:
        description: Tempo da rota (em minutos)
        type: integer
      tipo:
        type: integer
        description: Tipo da rota 1. Rodoviária 2. Aquaviaria 3. Mista
        enum:
        - 1
        - 2
        - 3
      id_firebase: 
        type: integer
```
