### ISSUE TITLE
Módulo Veículos - GET - Obter dados de um veículo específico

### ISSUE THREAD

**Issue by glcalil-ufg** [umarley/seteAPI#127]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-564f4cde-7fff-d592-af14-7b5da5358bb0"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:684px;height:54px;"><img src="https://lh6.googleusercontent.com/6CIzxeGRugM-jdydUn9GtIABn823elWlWdZY-GeWFj73a8oDyYf6D80XPl5MPG7qMXv4xrM2nAxAHNY6790loEVB-CygS0DBJV9FxMCeoZrq-G3kiHG1NifSoi3V08XqSoa_5pb3bqhL" width="684" height="54" style="margin-left:0px;margin-top:0px;" /></span></span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Exemplo de requisição:</span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:9pt;font-family:Consolas,sans-serif;color:#212121;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">GET </span><a href="https://sete.transportesufg.eng.br/veiculos/5201405/1" style="text-decoration:none;"><span style="font-size:9pt;font-family:Consolas,sans-serif;color:#1155cc;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">https://sete.transportesufg.eng.br/veiculos/5201405/1</span></a></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Resultado do experimento:</span></p><ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Retorno do HTTP está 200 (OK)</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">O resultado está diferente do esperado na API</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Está usando o seguinte formato&nbsp;</span></p></li></ul><p dir="ltr" style="line-height:1.295;margin-left: 36pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Consolas,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">{ ..., result: &quot;true&quot; }</span></p><ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Há campos do tipo _links, deve ser feito assim mesmo?</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Há vários campos NULL, verificar se isto é correto.</span></p></li></ul><br /><p dir="ltr" style="line-height:1.295;margin-left: 36pt;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:583px;height:520px;"><img src="https://lh6.googleusercontent.com/-058meJCKBzzqEkP_7voexD6TpE97qUsE_0h6gSTVJFogt1aAJ5Ub6cu7iad_jsSXIAYTLbNR7ITIqF8zEFK4S9rUqRFuefQQIyGztrfJeaR1i9nHhfcPm2ebKPqrYq_9xxfgnD6RTBF" width="583" height="520" style="margin-left:0px;margin-top:0px;" /></span></span></p><p dir="ltr" style="line-height:1.295;margin-left: 36pt;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="width:100px;display:inline-block;position:relative;"></span></span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Exemplo de requisição:</span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:9pt;font-family:Consolas,sans-serif;color:#212121;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">GET </span><a href="https://sete.transportesufg.eng.br/veiculos/520140599/1" style="text-decoration:none;"><span style="font-size:9pt;font-family:Consolas,sans-serif;color:#1155cc;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">https://sete.transportesufg.eng.br/veiculos/520140599</span><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#1155cc;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">/1</span></a></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Resultado do experimento:</span></p><ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Retorno do HTTP está 404 (NOT FOUND)</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">O resultado está diferente do esperado na API</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Está usando o seguinte formato&nbsp;</span></p></li></ul><p dir="ltr" style="line-height:1.295;margin-left: 36pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Consolas,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">{ result: &quot;false&quot;, messages : &ldquo;...&rdquo; }</span></p><br /><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:Consolas,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:576px;height:83px;"><img src="https://lh6.googleusercontent.com/PKzIRht0aHAwfDutYdt8pJ1k-7_TTPH5nKGYUtgiQ0z-8aLIRIqUh0bicKgBEHOYKYAwVveQ925zNiV7euu7Ip5FeMmszBKQFNWilxLRGuzvhAEmYORkMVzvHCDNyG0KVZHgAjYOdSoR" width="576" height="83" style="margin-left:0px;margin-top:0px;" /></span></span></p><br /><div dir="ltr" style="margin-left:-5.4pt;" align="left">

</div><br /></b>
</body>
</html>

**Comment by glcalil-ufg** [comment]
@umarley 
```yaml
get:
      tags:
      - veiculos
      summary: Obter dados de um veículo específico
      operationId: getVeiculoId
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: codigo_cidade
        description: Código do municipio que o veículo pertence
        required: true
        type: integer
      - in: path
        name: id_veiculo
        description: ID do veículo que se deseja consultar 
        required: true
        type: integer
      responses:
        200:
          description: Operação Realizada com Sucesso
          schema: 
            $ref: '#/definitions/veiculoCompleto'
        400:
          description: Parâmetros incorretos
        404:
          description: Veículo não encontrado
      security:
      - api_key: []
```
Modelo
```yaml
veiculoCompleto:
    type: object
    properties:
      codigo_cidade:
        type: integer
      id_veiculo:
        type: integer
      placa:
        type: string
      ano:
        type: integer
      modo:
        type: integer
        description: Modalidade do veículo 0. Rodoviário 1. Aquaviario
        enum:
        - 0
        - 1
      origem:
        type: integer
        description: Origem do veículo 1. Próprio 2. Terceirizado
        enum:
        - 1
        - 2
      km_inicial:
        type: number
      capacidade:
        type: integer
      km_atual:
        type: number
      tipo:
        type: integer
        description: Tipo do veículo 1. Ônibus 2. Micro-ônibus 3. Van 4. Kombi 5. Caminhão 6. Caminhonete 7. Motocicleta 8. Animal de tração 9. Lancha/Voadeira 10. Barco de madeira 11. Barco de alumínio 12. Canoa motorizada 13. Canoa a remo
        enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
      renavam:
        type: string
      manutencao:
        type: string
      marca:
        type: integer
      id_firebase:
        type: string
      ipva:
        type: number
        description: Valor do IPVA
      dpvat:
        type: number
        description: Valor do DPVAT
      seguro_anual:
        type: number
        description: Valor do Seguro anual
      consumo:
        type: number
        description: Consumo do veículo KM/L ou L/hora
      tipo_combustivel:
        type: string
        description: Tipo do combustível utilizado pelo veículo G - Gasolina D - Diesel E - Etanol N - Gás Natural O - Outro
        enum:
        - G
        - D
        - E
        - N
        - O
      numero_de_pneus:
        type: integer
      vida_util_do_pneu:
        type: number
      preco:
        type: number
      potencia_do_motor:
        type: string
      modelo:
        type: integer
      marca_str:
        type: string
      modo_str:
        type: string
      origem_str:
        type: string
      result:
        type: boolean  
    xml:
      name: Veículo
```
