### ISSUE TITLE
Módulo Rotas - GET - Obter dados de uma rota específica

### ISSUE THREAD

**Issue by glcalil-ufg** [umarley/seteAPI#130]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-3ef027ec-7fff-0414-ed6b-6995f3025621"><div dir="ltr" style="margin-left:-5.4pt;" align="left">
</div><br /><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:648px;height:53px;"><img src="https://lh3.googleusercontent.com/BYdejoMJ6HT0jrAN6MqKRnC2aCMpKsqtl2XPUDWu2qYMNhcMUJv9EGz3LZtJ8iYvo9p0NwyUqjEZc9N2xlCO6m5Eq1-zWNnqISIJEcIFJ4xbyDLFHKrRvOI4KGzIJ6xcQTyunIvZMnaZ" width="648" height="53" style="margin-left:0px;margin-top:0px;" /></span></span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Exemplo de requisição:</span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:9pt;font-family:Consolas,sans-serif;color:#212121;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">GET </span><a href="https://sete.transportesufg.eng.br/rotas/5201405/73170" style="text-decoration:none;"><span style="font-size:9pt;font-family:Consolas,sans-serif;color:#1155cc;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">https://sete.transportesufg.eng.br/rotas/5201405/73170</span></a></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Resultado do experimento:</span></p><ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Retorno do HTTP está 200 (OK)</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">O resultado está diferente do esperado na API</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Está usando o seguinte formato&nbsp;</span></p></li></ul><p dir="ltr" style="line-height:1.295;margin-left: 36pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Consolas,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">{ ..., total: &lt;valor&gt; }</span></p><ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Há campos do tipo _links, deve ser feito assim mesmo?</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;" role="presentation"><span style="font-size:11pt;font-family:Consolas,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Há vários campos NULL, verificar se está correto.</span></p></li></ul><p dir="ltr" style="line-height:1.295;margin-left: 36pt;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:Consolas,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:580px;height:418px;"><img src="https://lh4.googleusercontent.com/R5_-9OqPI6f0-7G3kay8HyIltsQ-sxoZo-u0TDqgzJjX9omg-kp-U54g3-38KIYfy4OFo2rVIEisCpQfOUjXCvUweC51UCVeAJL19A3whRl8pTn9jYf2Et-gyQ4lhphKn-J4lZYAfg-9" width="580" height="418" style="margin-left:0px;margin-top:0px;" /></span></span><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="width:100px;display:inline-block;position:relative;"></span></span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Exemplo de requisição:</span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:9pt;font-family:Consolas,sans-serif;color:#212121;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">GET </span><a href="https://sete.transportesufg.eng.br/rotas/5201405/73170" style="text-decoration:none;"><span style="font-size:9pt;font-family:Consolas,sans-serif;color:#1155cc;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">https://sete.transportesufg.eng.br/rotas/5201409995/73170</span></a></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Resultado do experimento:</span></p><ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Retorno do HTTP está 404 (NOT FOUND)</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">O resultado está diferente do esperado na API</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Está usando o seguinte formato&nbsp;</span></p></li></ul><p dir="ltr" style="line-height:1.295;margin-left: 36pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Consolas,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">{ result: &quot;false&quot;, messages : &ldquo;...&rdquo; }</span></p><br /><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:Consolas,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:576px;height:83px;"><img src="https://lh6.googleusercontent.com/PKzIRht0aHAwfDutYdt8pJ1k-7_TTPH5nKGYUtgiQ0z-8aLIRIqUh0bicKgBEHOYKYAwVveQ925zNiV7euu7Ip5FeMmszBKQFNWilxLRGuzvhAEmYORkMVzvHCDNyG0KVZHgAjYOdSoR" width="576" height="83" style="margin-left:0px;margin-top:0px;" /></span></span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Exemplo de requisição:</span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:9pt;font-family:Consolas,sans-serif;color:#212121;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">GET </span><a href="https://sete.transportesufg.eng.br/rotas/5201405/73170" style="text-decoration:none;"><span style="font-size:9pt;font-family:Consolas,sans-serif;color:#1155cc;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">https://sete.transportesufg.eng.br/rotas/5201405/73179990</span></a></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Resultado do experimento:</span></p><ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Retorno do HTTP está 404 (NOT FOUND)</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">O resultado está diferente do esperado na API</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Está usando o seguinte formato&nbsp;</span></p></li></ul><p dir="ltr" style="line-height:1.295;margin-left: 36pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Consolas,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">{ link_to_object, result: &quot;false&quot; }</span></p><ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:Consolas,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:Consolas,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Deveria realmente voltar um link para um objeto?</span></p></li></ul><br /><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Consolas,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:579px;height:141px;"><img src="https://lh5.googleusercontent.com/9dhX4PeB_e6ah79DtxLgUM6xNF4B2izmbkIU9thEO2zo3kFm4Q9gVkQb9fl6BXcQvO-ZhfyJFnidrzwgzHt-k6Q1Jkm-HdWw31vFuECIUwctBqz9g7nDxN0tSM06_UEczORpfPjCOIFi" width="579" height="141" style="margin-left:0px;margin-top:0px;" /></span></span></p></b><br class="Apple-interchange-newline">
</body>
</html>

**Comment by glcalil-ufg** [comment]
@umarley 
```yaml
 get:
      tags:
      - rotas
      summary: Obter dados de uma rota específica
      operationId: getRotaId
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: codigo_municipio
        description: Código do municipio que a rota pertence
        required: true
        type: integer
      - in: path
        name: id_rota
        description: ID da rota que se deseja consultar 
        required: true
        type: integer
      responses:
        200:
          description: Operação realizada com sucesso
          schema:
            $ref: '#/definitions/RotaGet'
        400:
          description: Parâmetros incorretos
        404:
          description: Rota não encontrada
      security:
      - api_key: []
 ```
Modelo
```yaml
 RotaGet:
    type: object
    properties:
      codigo_cidade:
        type: integer
      id_rota:
        type: integer
      nome:
        type: string
      km:
        description: Tamanho da rota (em km)
        type: number
      hora_ida_inicio:
        description: Horário de inicio da Ida no formato hh:mm
        type: string
      hora_ida_termino:
        description: Horário de inicio da Volta no formato hh:mm
        type: string
      da_porteira:
        type: string
        description: Tem porteira? S = Sim N = Não
        enum:
        - S
        - N
      da_mataburro:
        type: string
        description: Tem mata-burro? S = Sim N = Não
        enum:
        - S
        - N
      da_colchete:
        type: string
        description: Tem colchete? S = Sim N = Não
        enum:
        - S
        - N
      da_atoleiro:
        type: string
        description: Tem atoleiro? S = Sim N = Não
        enum:
        - S
        - N
      da_ponterustica:
        type: string
        description: Tem ponte rústica? S = Sim N = Não
        enum:
        - S
        - N
      turno_matutino:
        type: string
        description: Funciona no turno da manhã? S = Sim N = Não
        enum:
        - S
        - N
      turno_vespertino:
        type: string
        description: Funciona no turno da tarde? S = Sim N = Não
        enum:
        - S
        - N
      turno_noturno:
        type: string
        description: Funciona no turno da noite? S = Sim N = Não
        enum:
        - S
        - N      
      hora_volta_inicio:
        description: Horário de inicio da Volta no formato hh:mm
        type: string
      hora_volta_termino:
        description:  Horário de término da Volta no formato hh:mm
        type: string
      tempo:
        description: Tempo da rota (em minutos)
        type: integer
      tipo:
        type: integer
        description: Tipo da rota 1. Rodoviária 2. Aquaviaria 3. Mista
        enum:
        - 1
        - 2
        - 3
      id_firebase:
        type: string
      result:
        type: boolean
```
