### ISSUE TITLE
Módulo Usuários - POST - Criar um novo usuário no município sem autenticação

### ISSUE THREAD

**Issue by nataliasou** [umarley/seteAPI#140]
Exemplo de requisição:
POST https://sete.transportesufg.eng.br/registro/5201405 
Body:
{
  "nome": "João das Neves",
  "cpf": "90176459030",
  "telefone": "77991009100",
  "email": "joao-neves@gmail.com",
  "password": "953414f9f1ed8dfe1798e518e7fe0468",
  "tipo_permissao": "admin"
}

Resultado do experimento:
•	Retorno do HTTP está 201 - Created
•	O resultado não está na documentação da API
•	Está usando o seguinte formato 
{ result: "true", messages:{“id”: }
![image](https://user-images.githubusercontent.com/45390353/189025095-d25f9d8e-ef73-4014-adcd-e0f282de760b.png)

Exemplo de requisição:
POST https://sete.transportesufg.eng.br/registro/5201405 
Body:
{
  "nome": "João das Neves",
  "cpf": "90176459030",
  "telefone": "77991009100",
  "email": "joao-neves@gmail.com",
  "password": "953414f9f1ed8dfe1798e518e7fe0468",
  "tipo_permissao": "adn"  mudei aqui
}

Resultado do experimento:
•	Retorno do HTTP está 400 – Bad request
•	O resultado não está na documentação da API
•	Está usando o seguinte formato 
{ result: "false", messages:{ ... }
![image](https://user-images.githubusercontent.com/45390353/189025133-d84d537d-c6ea-442b-b563-02291d1b3819.png)

Exemplo de requisição:
POST https://sete.transportesufg.eng.br/registro/5201405 
Body:
{
  "nome": "João das Neves",
  "cpf": "90176459030",
  "telefone": "77991009100",
  "email": "joao-neves@gmail.com",
  "password": "", mudei aqui
  "tipo_permissao": "admin" 
}

Resultado do experimento:
•	Retorno do HTTP está 400 – Bad request
•	O resultado não está na documentação da API
•	Está usando o seguinte formato 
{ result: "false", messages:{ ... }
![image](https://user-images.githubusercontent.com/45390353/189025197-b11019eb-f914-41b3-be05-413ba83e1d4e.png)

Exemplo de requisição:
POST https://sete.transportesufg.eng.br/registro/5201405 
Body:
{
  "nome": "João das Neves",
  "cpf": "90176459030",
  "telefone": "77991009100",
  "email": "joao-neves@gmail.com", mudei aqui
  "password": " 953414f9f1ed8dfe1798e518e7fe0468",
  "tipo_permissao": "admin" 
}

Resultado do experimento:
•	Retorno do HTTP está 400 – Bad request
•	O resultado não está na documentação da API
•	Está usando o seguinte formato 
{ result: "false", messages:{ ... }
![image](https://user-images.githubusercontent.com/45390353/189025255-5e6b4d17-4a38-4f68-af1e-4ee75873ab0d.png)

Exemplo de requisição:
POST https://sete.transportesufg.eng.br/registro/5201405 
Body:
{
  "tipo_permissao": "admin" 
}

Resultado do experimento:
•	Retorno do HTTP está 400 – Bad request
•	O resultado não está na documentação da API
•	Está usando o seguinte formato 
{ result: "false", messages:{ ... }
![image](https://user-images.githubusercontent.com/45390353/189025310-018ec2d1-6ef6-4eea-a3b9-e88821a3b62e.png)

Exemplo de requisição:
POST https://sete.transportesufg.eng.br/registro/0  
Body:
{
  "nome": "João das Neves",
  "cpf": "90176459030",
  "telefone": "77991009100",
  "email": "joao-neves@gmail.com",
  "password": "953414f9f1ed8dfe1798e518e7fe0468",
  "tipo_permissao": "admin"
}

Resultado do experimento:
•	Retorno do HTTP está 400 – Bad request
•	O resultado não está na documentação da API
•	Está usando o seguinte formato 
{ result: "false", messages:{ ... }
![image](https://user-images.githubusercontent.com/45390353/189025344-0dc543c6-1d96-499c-9e6b-5692b580201d.png)

Exemplo de requisição:
POST https://sete.transportesufg.eng.br/registro/11111111111111111  
Body:
{
  "nome": "João das Neves",
  "cpf": "90176459030",
  "telefone": "77991009100",
  "email": "joao-neves@gmail.com",
  "password": "953414f9f1ed8dfe1798e518e7fe0468",
  "tipo_permissao": "admin"
}

Resultado do experimento:
•	Retorno do HTTP está 400 – Bad request
•	O resultado não está na documentação da API
•	Está usando o seguinte formato 
{ result: "false", messages:{ ... }
![image](https://user-images.githubusercontent.com/45390353/189025394-6efd28bd-93f5-4a7c-befa-fe2ae8d242fb.png)

**Comment by nataliasou** [comment]
@umarley 
```yaml
post:
      tags:
      - usuarios
      summary: Criar um novo usuário no municipio sem a necessidade de se autenticar
      description: Este endpoint deve ser usado após o usuário esta autenticado.
      operationId: createUserFirstAccess
      produces:
      - application/json
      parameters:
      - in: path
        name: codigo_cidade
        description: Código da cidade do usuário
        required: true
        type: integer
      - in: body
        name: body
        description: Created user object
        required: true
        schema:
          $ref: '#/definitions/Usuario'
      responses:
        201:
          description: Operação realizada com sucesso
          schema:
            $ref: '#/definitions/CreateResponse'
        400:
          description: Parâmetros inválidos
        404:
          description: Não encontrado
```

Model:
```yaml
Usuario:
    required:
     - nome
     - cpf
     - email
     - password
     - tipo_permissao
    type: object
    properties:
      nome:
        type: string
      cpf:
        type: string
      telefone:
        type: string
      email:
        type: string
      password:
        type: string
        format: md5
      tipo_permissao:
        type: string
        enum: [admin, leitor, editor]
        description: >
          admin - Usuário administrador  leitor - Usuário somente leitura editor - Usuário que ler e grava dados no sistema
```

Response:
```yaml
CreateResponse:
    type: object
    properties:
      result:
        type: boolean
      messages:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
              description: ID do objeto criado
```
