### ISSUE TITLE
Módulo Monitores - POST - Cadastrar um novo monitor no sistema SETE

### ISSUE THREAD

**Issue by nataliasou** [umarley/seteAPI#146]
![image](https://user-images.githubusercontent.com/45390353/189027709-e866f7e3-067a-40dd-b4f8-f2bc26050a6f.png)
Exemplo de requisição:
POST https://sete.transportesufg.eng.br/monitores/5201405 
Body:
![image](https://user-images.githubusercontent.com/45390353/189027752-5e156aec-bcec-4d2f-a59a-14829df549d8.png)
Resultado do experimento:
•	Retorno do HTTP está 200 - OK
•	O resultado está diferente do esperado na API
•	Está usando o seguinte formato 
{ ..., result: "true" }
•	Há vários campos NULL, verificar se é o correto com o Prof.  Marcos e o Umarley
•	Há campos do tipo _links, deve ser feito assim mesmo?
![image](https://user-images.githubusercontent.com/45390353/189027779-3ee861c8-0f83-4092-8535-f6961a288608.png)
Exemplo de requisição:
POST https://sete.transportesufg.eng.br/monitores/0 
Body:
![image](https://user-images.githubusercontent.com/45390353/189027819-8e7017ea-e998-42c9-a658-7b71a80ffec0.png)
Resultado do experimento:
•	Retorno do HTTP está 403 - Forbidden
•	O resultado não está especificado na documentação da API.
•	Está usando o seguinte formato 
{ result: "false", “messages”:... }
•	Há vários campos NULL, verificar se é o correto com o Prof.  Marcos e o Umarley
•	Há campos do tipo _links, deve ser feito assim mesmo?
![image](https://user-images.githubusercontent.com/45390353/189027847-96a18e41-a55b-4098-87b5-6bcf6335f412.png)
Exemplo de requisição:
POST https://sete.transportesufg.eng.br/monitores/5201405 
Body:
{
}

Resultado do experimento:
•	Retorno do HTTP está 400 – Bad request
•	O resultado não está especificado na documentação da API.
•	Está usando o seguinte formato 
{ result: "false", “messages”: ... }
![image](https://user-images.githubusercontent.com/45390353/189027902-c7a26e1a-5025-4fcd-9bdd-11925c1ce88d.png)
Exemplo de requisição:
POST https://sete.transportesufg.eng.br/monitores/5201405  
Body:
![image](https://user-images.githubusercontent.com/45390353/189027949-70415ee0-f5bd-4bcb-8873-4bc3d02603fb.png)

Resultado do experimento:
•	Retorno do HTTP está 400 – Bad request
•	O resultado não está especificado na documentação da API.
•	Está usando o seguinte formato 
{ result: "false", “messages”:... }
![image](https://user-images.githubusercontent.com/45390353/189027984-588c725e-da60-43fc-857b-4db6998001bb.png)

**Comment by nataliasou** [comment]
@umarley 
```yaml
post:
      tags:
      - monitores
      summary: Cadastrar um novo monitor no sistema SETE
      operationId: newMonitor
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: codigo_cidade
        description: Código do municipio que o monitor pertence
        required: true
        type: integer
      - in: body
        name: body
        description: Objeto contendo os dados do monitor
        required: true
        schema:
          $ref: '#/definitions/Monitor'
      responses:
        200:
          description: Operação realizada com sucesso
          schema:
            $ref: '#/definitions/CreateResponseMonitor'
        400:
          description: Parâmetros inválidos
        404:
          description: Recurso não encontrado
      security:
      - api_key: []
  ```

Model
```yaml
Monitor:
    type: object
    required:
     - cpf
     - nome
     - data_nascimento
     - vinculo
     - sexo
     - turno
    properties:
      cpf:
        type: string
      nome:
        type: string
      data_nascimento:
        description: Data de nascimento no formato dd/mm/yyyy
        type: string
      sexo:
        type: integer
        description: Sexo do Motorista 1. Masculino 2. Feminino 3. Não Informado
        enum:
        - 1
        - 2
        - 3
      telefone:
        type: string
      vinculo:
        type: integer
        description: Vínculo do motorista com a administração pública 1. Servidor efetivo 2. Servidor comissionado 3. Servidor terceirizado 4. Outro
        enum:
        - 1
        - 2
        - 3
        - 4
      salario:
        type: number
        description: Salário pago ao monitor
      turno_manha:
        type: string
        description: Trabalha no turno da manhã? S = Sim N = Não
        enum:
        - S
        - N
      turno_tarde:
        type: string
        description: Trabalha no turno da tarde? S = Sim N = Não
        enum:
        - S
        - N
      turno_noite:
        type: string
        description: Trabalha no turno da noite? S = Sim N = Não
        enum:
        - S
        - N
      loc_latitude:
        type: string
      loc_longitude:
        type: string
```

Response:
```yaml
CreateResponseMonitor:
    type: object
    properties:
      result:
        type: boolean
      messages:
        type: array
        items:
          type: object
          properties:
            cpf:
              type: string
              description: ID do objeto criado
```
