### ISSUE TITLE
Módulo Aluno - POST - Incluir um novo aluno no sistema

### ISSUE THREAD

**Issue by glcalil-ufg** [umarley/seteAPI#153]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-01108181-7fff-29e7-36d2-a03797329d19"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Módulo Aluno</span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:518px;height:52px;"><img src="https://lh6.googleusercontent.com/EeZgKbeU5MbbFM91XqKHqpQBObm4OtFI2dN22WCVDBAlKZ6DJnASnlw6ViXzsOywAhO_eRaAc872RODIpq8GFMkWLZGhAE0IRXHfmWdEYi39q2KXSTCPrTlNMjf053JjjshONHNebqoLiR3Bg2gTb5ZN4on7Vsx2YJbdT36o_NoqZFIF0GaBNGpzDw" width="518" height="52" style="margin-left:0px;margin-top:0px;" /></span></span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Exemplo de requisição:</span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:9pt;font-family:Consolas,sans-serif;color:#212121;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">POST </span><a href="https://sete.transportesufg.eng.br/alunos/5201405/1" style="text-decoration:none;"><span style="font-size:9pt;font-family:Consolas,sans-serif;color:#0563c1;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">https://sete.transportesufg.eng.br/aluno/5201405</span></a></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Path:</span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">codigo_cidade: 5201405</span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Body:</span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:585px;height:373px;"><img src="https://lh6.googleusercontent.com/B8yjLQopiWX9u8kpWj0siROVIDXJ7zhGFAuVpunaPVQq-Sk_lTTPZDRG-4hwyuS_LDAPZ5TlOOtv9p3zD89i6hfrN0lFP6kn7e2vkwfJJxJB7wj0xVgeD_kUfas8d1yHZvZKusSTmJdCGtln3bf1Usw8jqc1rJVfQRo41ytPJV576ox4-5BQS5QgZw" width="585" height="373" style="margin-left:0px;margin-top:0px;" /></span></span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Resultado do experimento:</span></p><ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Retorno do HTTP está 201 (CREATED)</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">O resultado está diferente do esperado na API</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Está usando o seguinte formato&nbsp;</span></p></li></ul><p dir="ltr" style="line-height:1.295;margin-left: 36pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Consolas,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">{ result: &quot;true&quot;, messages: {&ldquo;id&rdquo;: &lt;id_aluno&gt;} }</span></p><br /><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:585px;height:105px;"><img src="https://lh6.googleusercontent.com/8qmegvt6tSh8z1yXc9PrflClUhtrvZQEOHlu6VuSBgPP5h5Do84aZ070Il_lf89u0bfgWzv9MVerBCplvGB82vo0RPMORN5fJ2MW_a3Grj8UXde7dB4ZUqhnm4UOI3XgtNHagggelPaReB92Z3iCGK9RxnhzieccBHmtVRXi-ic1YlYIh4Ga-EySGA" width="585" height="105" style="margin-left:0px;margin-top:0px;" /></span></span></p><br /><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Exemplo de requisição:</span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:9pt;font-family:Consolas,sans-serif;color:#212121;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">POST </span><a href="https://sete.transportesufg.eng.br/alunos/5201405/1" style="text-decoration:none;"><span style="font-size:9pt;font-family:Consolas,sans-serif;color:#0563c1;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">https://sete.transportesufg.eng.br/aluno/52014059999</span></a></p><p dir="ltr" style="line-height:1.295;text-indent: 36pt;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">1 -&nbsp; Campo cidade errado;</span></p><p dir="ltr" style="line-height:1.295;text-indent: 36pt;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">2 - Campos obrigatórios faltando;</span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Resultado do experimento:</span></p><ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Retorno do HTTP está 403 (FORBIDDEN) e 400 (BAD REQUEST)</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">O resultado está diferente do esperado na API</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:11pt;font-family:'Palatino Linotype',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Está usando o seguinte formato&nbsp;</span></p></li></ul><p dir="ltr" style="line-height:1.295;margin-left: 36pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Consolas,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">{ result: &quot;false&quot;, messages : &ldquo;...&rdquo; }</span></p><br /><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Consolas,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:602px;height:172px;"><img src="https://lh5.googleusercontent.com/QbPQiKiz6hA0IGk0J-o9faETYoHsgQMfW5XXp2KzfafxmVb1p6F3hgcj_VkvnGrAGwc3hdLXzPpNGTZq_RbDxgykmap6rjQ5ei7cSp2zWt-pACuk-LXH-xPP7LKNRy7h634fMWj6gh-RZGbuaMVq9o6Alv5qfL-6dyTnAvCd8v3bEgppTKbn60aIZg" width="602" height="172" style="margin-left:0px;margin-top:0px;" /></span></span></p><br /><div dir="ltr" style="margin-left:-5.4pt;" align="left">
</div><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="width:100px;display:inline-block;position:relative;"></span></span></p></b><br class="Apple-interchange-newline">
</body>
</html>

**Comment by glcalil-ufg** [comment]
@umarley 
```yaml
post:
      tags:
      - alunos
      summary: Incluir um novo aluno no sistema
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: codigo_cidade
        description: Código da cidade na qual deseja cadastrar o aluno
        type: integer
        required: true
      - in: body
        name: body
        description: Dados do aluno a ser cadastrado
        required: true
        schema:
          $ref: '#/definitions/Aluno'
      responses:
        201:
          description: Operação realizada com sucesso
          schema:
            $ref: '#/definitions/CreateResponse'
        400:
          description: Parâmetros inválidos
        404:
          description: Não encontrado
      security:
      - api_key: []
```
Modelo Body
```yaml
Aluno:
    type: object
    required:
     - mec_tp_localizacao
     - nome
     - data_nascimento
     - sexo
     - cor
     - nivel
     - turno
    properties:
      loc_latitude:
        type: string
      loc_longitude:
        type: string
      loc_endereco:
        type: string
      loc_cep:
        type: string
      da_porteira:
        type: string
        description: Tem porteira? S = Sim N = Não
        enum:
        - S
        - N
      da_mataburro:
        type: string
        description: Tem mata-burro? S = Sim N = Não
        enum:
        - S
        - N
      da_colchete:
        type: string
        description: Tem colchete? S = Sim N = Não
        enum:
        - S
        - N
      da_atoleiro:
        type: string
        description: Tem atoleiro? S = Sim N = Não
        enum:
        - S
        - N
      da_ponterustica:
        type: string
        description: Tem ponte rústica? S = Sim N = Não
        enum:
        - S
        - N
      nome:
        type: string
      data_nascimento:
        description: Data de nascimento no formato dd/mm/yyyy
        type: string
      sexo:
        type: integer
        description: Sexo do Aluno 1. Masculino 2. Feminino 3. Não Informado
        enum:
        - 1
        - 2
        - 3
      cor:
        type: integer
        description: Cor/raça do Aluno 0. Não informada 1. Amarelo 2. Branco 3. Indigena 4. Pardo 5. Preto
        enum:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
      turno:
        type: integer
        description: Turno de estudo do Aluno 1. Matutino 2. Vespertino 3. Integral 4. Noturno
        enum:
        - 1
        - 2
        - 3
        - 4
      nivel:
        type: integer
        description: Nível do Aluno 1. Infantil 2. Fundamental 3. Médio 4. Superior 5. Outro
        enum:
        - 1
        - 2
        - 3
        - 4
        - 5
      nome_responsavel:
        type: string
      grau_responsavel:
        type: integer
        description: Grau de parentesco -1; Não informado 0. Pai, Mãe, Padrasto ou Madrasta 1. Avô ou Avó 2. Irmão ou Irmã 4. Outro Parente
        enum:
        - 0
        - 1
        - 2
        - 4
      mec_tp_localizacao:
        type: integer
        description: Localização do Aluno 1. Urbana 2. Rural
        enum:
        - 1
        - 2
      cpf:
        type: string
      def_caminhar:
        type: string
        description: Tem deficiência fisica? S = Sim N = Não
        enum:
        - S
        - N
      def_ouvir:
        type: string
        description: Tem deficiência auditiva? S = Sim N = Não
        enum:
        - S
        - N
      def_enxergar:
        type: string
        description: Tem deficiência visual? S = Sim N = Não
        enum:
        - S
        - N
      def_mental:
        type: string
        description: Tem deficiência mental? S = Sim N = Não
        enum:
        - S
        - N
    xml:
      name: Aluno
```
Modelo Response
```yaml
 CreateResponse:
    type: object
    properties:
      result:
        type: boolean
      messages:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
              description: ID do objeto criado
```
