### ISSUE TITLE
Módulo Usuários - GET - Listar todos os usuários

### ISSUE THREAD

**Issue by nataliasou** [umarley/seteAPI#95]
![image](https://user-images.githubusercontent.com/45390353/187085530-467ea63e-422e-405b-a489-f96196917c1c.png)
Exemplo de requisição:
GET https://sete.transportesufg.eng.br/users/sete/5201405
Resultado:
•	Retorno do HTTP está 200 (OK)
•	O resultado está diferente do esperado na API
•	Está usando o seguinte formato 
{ ..., “total”: 0, result: "true" }
•	Os últimos quatro campos de cada usuário estão como NULL, verificar se é o correto com o Prof.  Marcos e o Umarley
![image](https://user-images.githubusercontent.com/45390353/187086016-1f3878b4-4c8d-4802-b6dc-07ff550ae3fe.png)

Exemplo de requisição:
GET https://sete.transportesufg.eng.br/users/sete/0
Resultado do experimento:
•	Retorna 403 (forbidden)
•	Verificar com o professor se é isso mesmo que deveria voltar.
![image](https://user-images.githubusercontent.com/45390353/187086047-66067966-7b8f-4ee9-9c17-60ffbbd3efb6.png)

Exemplo de requisição:
GET https://sete.transportesufg.eng.br/usrs/sete/0
•	Retorna 404 (not found) é o esperado
•	Não possui mensagens de erro.
![image](https://user-images.githubusercontent.com/45390353/187086108-6465eebc-ce00-4f23-9f39-31234bd192fb.png)

**Comment by nataliasou** [comment]
@umarley 
```
get:
      tags:
      - usuarios
      summary: Listar todos os usuários do SETE de um municipio
      operationId: loginUser
      produces:
      - application/json
      parameters:
      - name: codigo_cidade
        in: path
        description: Código do município
        required: true
        type: integer
      responses:
        200:
          description: Operação realizada com sucesso
          schema:
              $ref: '#/definitions/ListaUsuario'
        400:
          description: Parâmetros incorretos
        403:
          description: Usuário sem permissão para acessar o município selecionado.
      security:
      - api_key: []
```

Modelo:
```
ListaUsuario:
    properties:
      data:
        type: array
        items:
          properties:
            codigo_cidade: 
              type: integer
            uid:
              type: string
            nome:
              type: string
            cpf:
              type: string
            telefone:
              type: string
            email:
              type: string
            password:
              type: string
            cidade:
              type: string
            estado:
              type: string
            cod_estado:
              type: integer
            init:
              type: string
            dt_criacao:
              type: string
            dt_alteracao:
              type: string
            id_usuario:
              type: integer
            nivel_permissao:
              type: string
            is_ativo:
              type: string
            is_liberado:
              type: string
            criado_por:
              type: string
            alterado_por:
              type: string
            dt_liberacao:
              type: string
            foto:
              type: string
      total:
        type: integer
      result:
        type: boolean
```
